In [2]:
import torch
import numpy as np

In [3]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
rand_tensor

tensor([[0.5820, 0.1836, 0.4910],
        [0.9049, 0.0663, 0.9241]])

In [8]:
rand_tensor.device

device(type='cpu')

In [9]:
torch.cuda.is_available()

False